### ISSUE TITLE
Error: Couldn't find preset "latest" relative to directory 

### ISSUE THREAD

**Issue by thomhess** [CroudSupport/vue-fullcalendar#68]
Hello,

I'm totally new to both Vue and FullCalendar, and having an issue I can't really understand. Maybe it's super-simple, maybe not. Here's the full error-message:

`ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/vue-full-calendar/components/FullCalendar.vue
Module build failed: Error: Couldn't find preset "latest" relative to directory "/Users/magnus/Documents/dev/todo-app/node_modules/vue-full-calendar"
    at /Users/magnus/Documents/dev/todo-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/magnus/Documents/dev/todo-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/magnus/Documents/dev/todo-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/magnus/Documents/dev/todo-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/magnus/Documents/dev/todo-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/magnus/Documents/dev/todo-app/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/magnus/Documents/dev/todo-app/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/magnus/Documents/dev/todo-app/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/magnus/Documents/dev/todo-app/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/magnus/Documents/dev/todo-app/node_modules/babel-loader/lib/index.js:175:20)
 @ ./node_modules/vue-full-calendar/components/FullCalendar.vue 4:0-122
 @ ./node_modules/vue-full-calendar/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js`

**Comment by BrockReece** [comment]
Ooops, I am getting the same on the lastest release.
I will look into it.

In the meantime, you can try using v2.1.2

**Comment by BrockReece** [comment]
Ok this should be fixed in v2.1.4
If you can update/upgrade your version of vue-full-calendar and try again, it should work.

Sorry about that.

**Comment by thomhess** [comment]
Thanks, works like a charm!

**Comment by BrockReece** [comment]
Awesome :)

**Comment by bm2ilabs** [comment]
i am getting this issue i don't know if it's related to the package it self or not 

```
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/bm2ilabs/Code/eventmed/node_modules/vue-full-calendar"
    at /Users/bm2ilabs/Code/eventmed/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/bm2ilabs/Code/eventmed/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/bm2ilabs/Code/eventmed/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/bm2ilabs/Code/eventmed/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/bm2ilabs/Code/eventmed/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/bm2ilabs/Code/eventmed/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/bm2ilabs/Code/eventmed/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/bm2ilabs/Code/eventmed/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/bm2ilabs/Code/eventmed/node_modules/babel-loader/lib/index.js:46:20)
    at /Users/bm2ilabs/Code/eventmed/node_modules/babel-loader/lib/fs-cache.js:79:18
    at ReadFileContext.callback (/Users/bm2ilabs/Code/eventmed/node_modules/babel-loader/lib/fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

 @ ./~/vue-full-calendar/components/FullCalendar.vue 3:2-220

```

**Comment by BrockReece** [comment]
Hi @bm2ilabs 

What does your babel config look like?

**Comment by bm2ilabs** [comment]
@BrockReece i figured the issue , i installed all the missing plugin , thank you
