### ISSUE TITLE
Package.json has a bug?

### ISSUE THREAD

**Issue by ralts00** [CroudSupport/vue-fullcalendar#82]
Hi, could you help me with an error when i'm implementing the module:

package.json has a devDependency:

"babel-preset-es2015": "^6.24.1"

But when i run `npm install vue-full-calendar` and run my vue project i get the error below:

```sh
 ERROR  Failed to compile with 1 errors                                                      15:42:48

 error  in ./~/vue-full-calendar/components/FullCalendar.vue

Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/vue-full-calendar"
    at /Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/ralts00/Projects/Startegyvb/Worky/hr-front/node_modules/babel-loader/lib/index.js:163:20)

 @ ./~/vue-full-calendar/components/FullCalendar.vue 4:2-96
 @ ./~/vue-full-calendar/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

If i move on the package.json the devDependency to dependencies, i get run it successfuly.

**Comment by BrockReece** [comment]
Thanks, I think the Vue cli has changed their babel deps since I wrote this package, so I think I need to add the babel 2015 preset to the normal devs. Thanks for reminding me.

**Comment by BrockReece** [comment]
Hi @ralts00 

I have removed this dependency from this package now and have created a PR.
It is passing all tests but could you help me test it?

I am happy to create a prerelease version on NPM if that helps?

**Comment by ralts00** [comment]
I have testing with the changes and it works now !

Thank you for the quick fix 😬

**Comment by BrockReece** [comment]
Awesome, thanks

**Comment by BrockReece** [comment]
v2.5.1 is live with these changes.
Thanks for your help.
